[package]
name = "silicone"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
circular-buffer = "1.0.0"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
libc = "0.2.170"

